dynobo/normcap

- .github/workflows/test.yml
> Add tests for mac and windows

- .github/workflows/release.yml
- normcap/handlers/magic_handler.py
Somewhat slower, but a little bit more accurate. imho worth it.
> Switch to best training data on Windows

- CHANGELOG.md
- Pipfile
- Pipfile.lock
- normcap/__init__.py
- normcap/handlers/enhance_img_handler.py
- normcap/handlers/ocr_handler.py
- normcap/magics/email_magic.py
- normcap/magics/url_magic.py
- setup.cfg
- setup.py
- tests/images/test_images.py
- tests/test_data_model.py
- tests/test_normcap.py
> Update PyInstaller to be safe regarding known vulnerability

- setup.py
- Docu
- Missed dep in setup.py
> Merge very small changes

- CHANGELOG.md
- README.md
- normcap/handlers/ocr_handler.py
> Add changelog; Update readme

- CHANGELOG.md
- README.md
- normcap/__init__.py
- normcap/handlers/notification_handler.py
- normcap/ressources/win_installer.nsis
- requirements.txt
- setup.cfg
- setup.py
- tests/test_normcap.py
- Handle missing dependencies for the notification more gracefully
- Add linux dependencies necessary for notifications to the README
- Update version of python package dependencies
> Minor changes.

- CHANGELOG.md
- README.md
- normcap/__init__.py
- normcap/common/utils.py
- normcap/handlers/ocr_handler.py
- normcap/ressources/win_installer.nsis
- setup.cfg
- setup.py
- tests/test_normcap.py
> Add workaround for tesseract 4.0.x

- CHANGELOG.md
- build.py
* Switch to dylibbundler for MacOS dependency #199
Replaces custom bundling logic.
* Update changelog
> Introduce dynlib bundler

- CHANGELOG.md
- src/normcap/app.py
- src/normcap/gui/settings_menu.py
- src/normcap/gui/system_info.py
- src/normcap/gui/utils.py
- src/normcap/utils.py
> Introduce tessdata config folder for flatpak 

- CHANGELOG.md
- src/normcap/ocr/enhance.py
> Add backwards compatibility of to pillow < 9.2.0

- docs/index.html
> docs: update faq info on qt platform plugin error

- CHANGELOG
- docs/index.html
- normcap/gui/tray.py
- normcap/utils.py
- tests/test_utils.py
> fix(gui): exit through system tray is broken #457

- README.md
- docs/index.html
> docs: update install python version on windows to fix #465

- CHANGELOG
- normcap/gui/notification.py
- normcap/gui/tray.py
- tests/tests_gui/test_notification.py
> feat(gui): add clickable (qt)-notifications

- normcap/resources/locales/sv_SE/LC_MESSAGES/messages.po
Hi,
Here's Swedish translation for NormCap. I enjoy this handy application very much. Thanks!
> Create Swedish messages.po

- .github/ISSUE_TEMPLATE/bug_report.yml
Note to me: Wait with merging until release of 0.5.0 beta 1
> chore: adjust debug command to new simplified path

- README.md
This adds [PowerToys Text Extractor](https://learn.microsoft.com/en-us/windows/powertoys/text-extractor) as similar tool.
Source code at https://github.com/microsoft/PowerToys/tree/main/src/modules/PowerOCR/PowerOCR
> Add PowerToys Text Extractor

- normcap/resources/locales/ru_RU/LC_MESSAGES/messages.po
Full translation. If I didn't miss anything :)
...and I suggest correcting the "thenthen" error, and correct the text "Donate for coffee"
> Update ru messages.po

- normcap/resources/locales/es_ES/LC_MESSAGES/messages.po
> update spanish translation

- CHANGELOG
- normcap/gui/menu_button.py
- normcap/gui/tray.py
- normcap/resources/locales/de_DE/LC_MESSAGES/messages.po
- normcap/resources/locales/es_ES/LC_MESSAGES/messages.po
- normcap/resources/locales/fr_FR/LC_MESSAGES/messages.po
- normcap/resources/locales/hi_IN/LC_MESSAGES/messages.po
- normcap/resources/locales/it_IT/LC_MESSAGES/messages.po
- normcap/resources/locales/pl_PL/LC_MESSAGES/messages.po
- normcap/resources/locales/pt_PT/LC_MESSAGES/messages.po
- normcap/resources/locales/ru_RU/LC_MESSAGES/messages.po
- normcap/resources/locales/sv_SE/LC_MESSAGES/messages.po
- normcap/resources/locales/uk_UA/LC_MESSAGES/messages.po
- normcap/resources/locales/zh_CN/LC_MESSAGES/messages.po
Fix typos that were reported in #611.
> fix(gui): typos in ui text; update changelog

- normcap/resources/locales/uk_UA/LC_MESSAGES/messages.po
Completely implemented translation into Ukrainian
> Update uk_UA messages.po

- CHANGELOG
- normcap/screengrab/handlers/dbus_portal.py
Try to fix for https://github.com/dynobo/normcap/issues/643
> fix(screengrab): file url parsing error in case of quoted special chars

- CHANGELOG
- normcap/gui/window.py
- normcap/resources/locales/README.md
> fix(gui): add workaround for showFullScreen

- normcap/resources/locales/zh_CN/LC_MESSAGES/messages.po
> feat(lang): add zh-CN

- docs/usage.md
- pyproject.toml
Revise the documentation to reflect the new detection settings and clarify the capture modes available in the settings menu.
> Update documentation for detection settings

- CHANGELOG
- normcap/gui/tray.py
- normcap/screenshot/__init__.py
- normcap/screenshot/handlers/gnome_screenshot.py
- normcap/screenshot/main.py
- normcap/screenshot/models.py
- normcap/screenshot/system_info.py
- normcap/utils.py
- tests/test_utils.py
- tests/tests_screengrab/test_main.py
Hopefully this can mitigate screenshot issue on Wayland at least in _some_ cases...
> feat: add gnome-screenshot as screenshot handler

- normcap/clipboard/handlers/xclip.py
- normcap/clipboard/handlers/xsel.py
- normcap/clipboard/system_info.py
- normcap/detection/ocr/tesseract.py
- normcap/gui/notification.py
- normcap/screenshot/handlers/dbus_portal.py
- normcap/screenshot/handlers/gnome_screenshot.py
- normcap/screenshot/handlers/grim.py
- normcap/screenshot/handlers/qt.py
- normcap/screenshot/permissions.py
- normcap/screenshot/system_info.py
Try to achieve BSD compatibility by assuming BSD == Linux.
This is experimental. If it it turns out BSD requires more specific changes, I might remove that again to avoid the addition effort mainting compatibility with yet another OS.
> feat: support BSD experimentally by assuming bsd == linux
